<%@ page language="java" contentType="javascript/x-javascript; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean"%>
<%--语言包 包含脚本所用中文--%>
var SapControls_Lang = {
	isLoadData:"<bean:message bundle='tib-sap' key='sapPlugin.isLoadData'/>",
	selectDownList:"<bean:message bundle='tib-sap' key='sapPlugin.selectDownList'/>",
	selectShowValue:"<bean:message bundle='tib-sap' key='sapPlugin.selectShowValue'/>",
	selectShowDesc:"<bean:message bundle='tib-sap' key='sapPlugin.selectShowDesc'/>",
	selectActualValue:"<bean:message bundle='tib-sap' key='sapPlugin.selectActualValue'/>",
	pluginName:"<bean:message bundle='tib-sap' key='sapPlugin.pluginName'/>",
	select:"<bean:message bundle='tib-sap' key='sapPlugin.select'/>",
	choose:"<bean:message bundle='tib-sap' key='sapPlugin.choose'/>",
	mappingTip:"<bean:message bundle='tib-sap' key='sapPlugin.tip.mappingTip'/>",
	mustSelect:"<bean:message bundle='tib-sap' key='sapPlugin.tip.mustSelect'/>",
	showTip:"<bean:message bundle='tib-sap' key='sapPlugin.tip.showTip'/>",
	descTip:"<bean:message bundle='tib-sap' key='sapPlugin.tip.descTip'/>",
	actualTip:"<bean:message bundle='tib-sap' key='sapPlugin.tip.actualTip'/>",
	
	dataSource : "<bean:message bundle='tib-sap' key='sapPlugin.controls.dataSource'/>",
	chooseFunc : "<bean:message bundle='tib-sap' key='tibSapMapping.lang.chooseFunc'/>",
	funcType : "<bean:message bundle="tib-sap" key="tibSapMapping.lang.funcType"/>",
	pleaseChooseDataSource : "<bean:message bundle="tib-sap" key="sapPlugin.controls.pleaseChooseDataSource"/>",
	loadingXmlTemplate : "<bean:message bundle="tib-sap" key="sapPlugin.controls.loadingXmlTemplate"/>",
	inputParam : "<bean:message bundle="tib-sap" key="sapPlugin.controls.inputParam"/>",
	add : "<bean:message bundle="tib-sap" key="sapPlugin.controls.add"/>",
	chooseField : "<bean:message bundle="tib-sap" key="sapPlugin.controls.chooseField"/>",
	mappingList : "<bean:message bundle="tib-sap" key="sapPlugin.controls.mappingList"/>",
	button : "<bean:message bundle="tib-sap" key="sapPlugin.controls.button"/>",
	text : "<bean:message bundle="tib-sap" key="sapPlugin.controls.text"/>",
	icon : "<bean:message bundle="tib-sap" key="sapPlugin.controls.icon"/>",
	sapDataByDialog : "<bean:message bundle="tib-sap" key="sapPlugin.controls.sapDataByDialog"/>",
	sapDataBySelect : "<bean:message bundle="tib-sap" key="sapPlugin.controls.sapDataBySelect"/>",
	sapDataByList : "<bean:message bundle="tib-sap" key="sapPlugin.controls.sapDataByList"/>",
	listStyle : "<bean:message bundle="tib-sap" key="sapPlugin.controls.listStyle"/>",
	pleaseChooseMappingList : "<bean:message bundle="tib-sap" key="sapPlugin.controls.pleaseChooseMappingList"/>",
	
	serial : "<bean:message bundle="tib-sap" key="sapPlugin.controls.serial"/>",
    total : "<bean:message bundle="tib-sap" key="sapPlugin.controls.total"/>",
    countRow : "<bean:message bundle="tib-sap" key="sapPlugin.controls.countRow"/>",
    index : "<bean:message bundle="tib-sap" key="sapPlugin.controls.index"/>",
    previous : "<bean:message bundle="tib-sap" key="sapPlugin.controls.previous"/>",
    next : "<bean:message bundle="tib-sap" key="sapPlugin.controls.next"/>",
    last : "<bean:message bundle="tib-sap" key="sapPlugin.controls.last"/>",
    previousTen : "<bean:message bundle="tib-sap" key="sapPlugin.controls.previousTen"/>",
    nextTen : "<bean:message bundle="tib-sap" key="sapPlugin.controls.nextTen"/>",
    search : "<bean:message bundle="tib-sap" key="sapPlugin.controls.search"/>",
    typeface : "<bean:message bundle="tib-sap" key="sapPlugin.controls.typeface"/>",
    noData : "<bean:message bundle="tib-sap" key="sapPlugin.controls.noData"/>"
};
